### ISSUE TITLE
Build failed on current debian oldstable (squeeze)

### ISSUE THREAD

**Issue by MarkusNeviadomski** [dominikschulz/VBoxAdm#12]
Hi folks,
maybe something is missing at my system, but i can not build the solution, because of an error with Logger.pm. Can you help me with this problem?

```
/usr/bin/perltidy -syn -l=160 -nce -nbl -b lib/VWebAdm/DNS.pm
```

build/filepp.pl -u -D@BUILDDATE@=2016-02-28 -D@VERSION@=0.2.32 -D@LIBDIR@="/usr/share/perl5" -D@CFGDIR@="/etc" lib/VWebAdm/L10N.ipm -o lib/VWebAdm/L10N.pm && \
/usr/bin/perltidy -syn -l=160 -nce -nbl -b lib/VWebAdm/L10N.pm
make: **\* No rule to make target lib/VWebAdm/Logger.pm', needed byall'. Stop.

Can you help me with this issue?

**Comment by dominikschulz** [comment]
Hi, unfortunately I haven't been able to pay much attention to this project lately. I can't promise when I may be able to investigate this.
